# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6950afca2d3c89db8faaa124a3cff8cd2d2681e5b4a09da0e07f1b3bb84c5031892045e2dd8d3ad311bf71bbb1ed0312270d6c9f3dfa5f250072f55d9027bdf5

test:
  secret_key_base: 6ee438cf4526d1515b984f79b23e157b7f62007c24b4b3ae2509352efcfd2190e646dd5e790be987e60ef7f3b480d5e0d32642bb44dc9a927178c1bdf6fae3b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
